name: 'Create Zip File'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Zip File
      run: zip -r DisposableRanks.zip . -x ".git/*" ".github/*"
    - name: Release to Github
      run: echo "Release"
